name = "FarmSim"
uuid = "c04e78ac-9578-4f6f-9b79-2c47f94b5e51"
version = "1.0.0-DEV"
authors = ["grahamstark <graham.stark@virtual-worlds.biz> and contributors"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
PanelDataTools = "f8e8dcbf-c8af-4c89-b3d0-30e7f728b8cf"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
CSV = "0.10.15"
CategoricalArrays = "1"
Chain = "1"
DataFrames = "1,2"
DataStructures = "0,1"
Dates = "1"
PanelDataTools = "0,1"
PrettyTables = "3,4"
Reexport = "1,2"
StatsBase = "0,1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
