name = "FarmSim"
uuid = "c04e78ac-9578-4f6f-9b79-2c47f94b5e51"
version = "1.0.0-DEV"
authors = ["grahamstark <graham.stark@virtual-worlds.biz> and contributors"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
PanelDataTools = "f8e8dcbf-c8af-4c89-b3d0-30e7f728b8cf"

[compat]
CSV = "0.10.15"
CategoricalArrays = "1.0.2"
Chain = "1.0.0"
DataFrames = "1.8.1"
DataStructures = "0.19.1"
Dates = "1.11.0"
PanelDataTools = "0.3.0"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
